openapi: 3.0.0
info:
  title: iFit Validate TV-App Purchase Transaction API
  description: Proposed BrightAPI-to-iFitAPI purchase transaction validation & subscription entitlement grant
  version: 1.0.6
  contact: {}
components:
  securitySchemes:
    auth0:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: /oauth/token
          scopes:
            read: read
            write: write
  schemas:
    ValidateSubscriptionRequest:
      type: object
      required:
        - type
        - userId
        - applicationId
      properties:
        type:
          type: string
          enum: [android, firetv, roku, tvos]
        userId:
          type: string
          example: 58951c6ea396e6290030ff71
        applicationId:
          type: string
          enum:
            - ai.bright.ifit.tvos.qa # tvOS Beta env, BrightAI dev account
            - ai.bright.ifit.tvos.release # tvOS Prod env, iFit dev account
            - ai.bright.ifit.androidtv.beta # Android Beta env, BrightAI dev account
            - com.ifit.palantir.androidtv # Android Prod env, iFit dev account
            - ai.bright.ifit.amazonfire.beta # Amazon Beta env, BrightAI dev account
            - com.ifit.palantir.amazonfire # Amazon Prod env, iFit dev account
            - roku.ifit.tv.beta # Roku Beta env, BrightAI dev account
            - roku.ifit.tv.prod # Roku Prod env, iFit dev account
      discriminator:
        propertyName: type
    AndroidTVValidateSubscriptionRequest:
      allOf:
        - $ref: '#/components/schemas/ValidateSubscriptionRequest'
        - type: object
          required:
            - applicationId
            - subscriptionId
            - purchaseToken
          properties:
            type:
              type: string
              example: android
            applicationId:
              type: string
              example: ai.bright.ifit.androidtv.beta
            subscriptionId:
              type: string
              example: ifryme # TODO eventually need to confirm this example
            purchaseToken:
              type: string
              example: e2fFzZ...jg30TgwN30=
    FireTVValidateSubscriptionRequest:
      allOf:
        - $ref: '#/components/schemas/ValidateSubscriptionRequest'
        - type: object
          required:
            - receiptId
            - fireTvUserId
          properties:
            type:
              type: string
              example: firetv
            applicationId:
              type: string
              example: ai.bright.ifit.amazonfire.beta
            fireTvUserId:
              type: string
              example: l3HL7XppEMhrOGDnur9-ulvqomrSg6qyODKmah76lJU=
            receiptId:
              type: string
              example: wE1EG1gsEZI9q9UnI5YoZ2OxeoVKPdR5bvPMqyKQq5Y=:1:11
    RokuValidateSubscriptionRequest:
      allOf:
        - $ref: '#/components/schemas/ValidateSubscriptionRequest'
        - type: object
          required:
            - transactionId
          properties:
            type:
              type: string
              example: roku
            applicationId:
              type: string
              example: roku.ifit.tv.beta
            transactionId:
              type: string
              example: d9dbdfecc5cc41cbb881ab750135029b
    TVOSValidateSubscriptionRequest:
      allOf:
        - $ref: '#/components/schemas/ValidateSubscriptionRequest'
        - type: object
          required:
            - receiptData
            - subscriptionId # might not be necessary
          properties:
            type:
              type: string
              example: tvos
            applicationId:
              type: string
              example: ai.bright.ifit.tvos.qa
            receiptData:
              type: string
              example: e2fFzZ...jg30TgwN30=
            subscriptionId:
              type: string
              example: 3jklj
    ValidateSubscriptionError:
      description: Parsed response from respective IAP store transaction validation API. If code == 2xx, retryable = false, do not retry. If code != 2xx, retryable = true, may be worth retrying.
      type: object
      required:
        - code
        - title
        - message
        - retryable
      properties:
        code:
          type: integer
          nullable: true
        title:
          type: string
          nullable: true
        message:
          type: string
        retryable:
          type: boolean
    ValidateSubscriptionResponse:
      description: If isEntitled == true proceed, else an error object is also included with the response
      type: object
      required:
        - isEntitled
      properties:
        isEntitled:
          type: boolean
        error:
          $ref: '#/components/schemas/ValidateSubscriptionError'
    UserSubscriptionInfoResponse:
      description: ''
      type: object
      required:
        - accountSource
        - sku
        - subscriptionManagementUrl
      properties:
        accountSource:
          type: string
          enum:
            - none
            - icon
            - android
            - ios
            - amazon
            - firetv
            - roku
            - tvos
            # - androidtv
        sku:
          type: string
        subscriptionManagementUrl:
          type: string
          enum:
            - https://www.ifit.com/settings/membership-plan
            - https://www.amazon.com/yourmembershipsandsubscriptions?ref_=ya_d_l_mng_subscriptions
            - https://play.google.com/store/account/subscriptions
            - https://support.apple.com/en-us/HT202039
            # - https://www.planetfitness.com/login
            - https://my.roku.com/account/subscriptions
            - https://www.amazon.com/yourmembershipsandsubscriptions
paths:
  /v1/tv-app/validate:
    post:
      summary: Returns whether user is entitled to their purchase transaction
      description: Proxy validation of purchase transaction to between iFitAPI & respective appstore API and performs the required updates on the user so they are entitled to what they have purchased
      requestBody:
        required: true
        content:
          application/json:
            schema:
              oneOf:
                - $ref: '#/components/schemas/AndroidTVValidateSubscriptionRequest'
                - $ref: '#/components/schemas/FireTVValidateSubscriptionRequest'
                - $ref: '#/components/schemas/RokuValidateSubscriptionRequest'
                - $ref: '#/components/schemas/TVOSValidateSubscriptionRequest'
              discriminator:
                propertyName: type
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidateSubscriptionResponse'
        '401':
          description: 'Unauthorized token header'
        '400':
          description: 'Bad request parameters'
        '404':
          description: 'User or puchase item associated with the transaction was not found'
        '500':
          description: 'Something went wrong when attempting to entitle the user or general internal server error'
      tags:
        - Validate Purchase Transaction
  /v1/tv-app/user-subscription-info/{userId}:
    get:
      summary: Returns some specific user subscription info
      description: Provides particular user subscription info for BrightAI to cater what is displayed in the TV App purchase products catalogue
      responses:
        '200':
          description: '200'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserSubscriptionInfoResponse'
        '401':
          description: 'Unauthorized token header'
        '404':
          description: 'User with the provided id was not found'
        '500':
          description: 'Internal server error'
